ifeq ($(subdir),string)
sysdep_routines += memcpy-aligned memcpy-unaligned memcpy-lasx \
		   memset-aligned memset-unaligned memset-lsx memset-lasx \
		   memmove-unaligned memmove-lsx memmove-lasx \
		   memchr-aligned memchr-lsx memchr-lasx \
		   memrchr-generic memrchr-lsx memrchr-lasx \
		   memcmp-aligned memcmp-lsx memcmp-lasx \
		   rawmemchr-aligned rawmemchr-lsx rawmemchr-lasx \
		   strchr-aligned strchr-unaligned strchr-lsx strchr-lasx \
		   strrchr-aligned strrchr-lsx strrchr-lasx \
		   strlen-aligned strlen-unaligned strlen-lsx strlen-lasx \
		   strnlen-aligned strnlen-unaligned strnlen-lsx strnlen-lasx \
		   strchrnul-aligned strchrnul-unaligned strchrnul-lsx strchrnul-lasx \
		   strncmp-aligned strncmp-unaligned strncmp-lsx \
		   strcpy-aligned strcpy-unaligned strcpy-lsx \
		   stpcpy-aligned stpcpy-lsx \
		   strcmp-aligned strcmp-unaligned strcmp-lsx
endif
