ifeq ($(subdir),string)
sysdep_routines += memcpy-aligned memcpy-unaligned memcpy-lasx \
		   memset-aligned memset-unaligned memset-lasx memset-lsx \
		   memmove-unaligned memmove-lsx \
		   memchr-aligned memchr-lsx \
		   memrchr-generic memrchr-lsx \
		   memcmp-aligned memcmp-lsx \
		   rawmemchr-aligned rawmemchr-lsx \
		   strchr-aligned strchr-unaligned strchr-lsx \
		   strrchr-aligned strrchr-lsx \
		   strlen-aligned strlen-unaligned strlen-lsx \
		   strnlen-aligned strnlen-unaligned strnlen-lsx \
		   strchrnul-aligned strchrnul-unaligned strchrnul-lsx \
		   strncmp-aligned strncmp-unaligned strncmp-lsx \
		   strcpy-aligned strcpy-unaligned strcpy-lsx
endif
