ifeq ($(subdir),string)
sysdep_routines += memcpy-aligned memcpy-unaligned memcpy-lasx \
		   memset-aligned memset-unaligned memset-lasx memset-lsx \
		   memmove-unaligned memmove-lsx \
		   memchr-aligned memchr-lsx \
		   memrchr-generic memrchr-lsx \
		   memcmp-aligned memcmp-lsx
endif
